"""Canonical defaults shared by persisted and in-memory simulation settings."""

DEFAULT_TICK_INTERVAL_SECONDS = 1.0
DEFAULT_SIMULATION_STEP_SECONDS = 5
DEFAULT_SPEED_MULTIPLIER = 1.0
DEFAULT_RANDOM_SEED = 42
DEFAULT_PERSIST_EVERY_N_TICKS = 1
DEFAULT_TICK_INTERVAL_MS = int(DEFAULT_TICK_INTERVAL_SECONDS * 1000)
