"""Leakage-safe feature engineering for future anomaly-model training."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import timedelta

import numpy as np
import pandas as pd

from app.ml.preprocessing import TrainingDatasetResult


METADATA_COLUMNS = (
    "reading_timestamp",
    "station_id",
    "tank_id",
    "pump_id",
    "simulation_run_id",
    "sequence_number",
    "source_type",
)

PUMP_ANOMALY_FEATURE_NAMES = (
    "flow_rate", "pressure", "motor_current", "pump_temperature", "error_count",
    "working_duration", "data_quality_score", "hour_of_day", "day_of_week",
    "is_weekend", "flow_rate_change", "pressure_change", "motor_current_change",
    "pump_temperature_change", "error_count_change", "flow_rate_change_5min",
    "motor_current_change_5min", "average_flow_rate_30min", "pressure_std_30min",
    "pump_temperature_change_30min",
)

TANK_ANOMALY_FEATURE_NAMES = (
    "tank_level", "true_tank_level", "temperature", "water_level", "error_count",
    "data_quality_score", "hour_of_day", "day_of_week", "is_weekend",
    "tank_level_change", "temperature_change", "water_level_change", "error_count_change",
    "temperature_change_30min", "water_level_change_30min",
)


@dataclass(frozen=True)
class FeatureEngineeringSummary:
    """Counts explaining how clean training readings became model rows."""

    input_rows: int
    pump_candidate_rows: int
    tank_candidate_rows: int
    pump_rows: int
    tank_rows: int
    dropped_rows_missing_history_or_values: int
    dropped_rows_non_finite: int


@dataclass(frozen=True)
class FeatureEngineeringResult:
    """Independent, model-ready pump and tank feature matrices with metadata."""

    features: dict[str, pd.DataFrame]
    metadata: dict[str, pd.DataFrame]
    feature_names: dict[str, tuple[str, ...]]
    summary: FeatureEngineeringSummary


class AnomalyFeatureEngineer:
    """Transform clean chronological readings without querying or changing the DB.

    The persistence layer stores tank and pump readings as different rows.  Two
    feature families avoid inventing values for the signals absent from each
    row type. The same public family methods can later be used with a bounded
    history plus one live reading.
    """

    def engineer(self, dataset: TrainingDatasetResult | pd.DataFrame) -> FeatureEngineeringResult:
        """Create deterministic, finite matrices from a Stage 8.1 dataset."""

        raw = dataset.dataframe if isinstance(dataset, TrainingDatasetResult) else dataset
        prepared = self._prepare(raw)
        pump_candidates = prepared[prepared["pump_id"].notna()].copy()
        # Pump observations also reference a tank; tank-only rows are the
        # records that carry the tank sensor values generated by persistence.
        tank_candidates = prepared[
            prepared["tank_id"].notna() & prepared["pump_id"].isna()
        ].copy()
        pump_features, pump_metadata, pump_drop = self.build_pump_features(pump_candidates)
        tank_features, tank_metadata, tank_drop = self.build_tank_features(tank_candidates)
        return FeatureEngineeringResult(
            features={"pump": pump_features, "tank": tank_features},
            metadata={"pump": pump_metadata, "tank": tank_metadata},
            feature_names={
                "pump": PUMP_ANOMALY_FEATURE_NAMES,
                "tank": TANK_ANOMALY_FEATURE_NAMES,
            },
            summary=FeatureEngineeringSummary(
                input_rows=len(prepared),
                pump_candidate_rows=len(pump_candidates),
                tank_candidate_rows=len(tank_candidates),
                pump_rows=len(pump_features),
                tank_rows=len(tank_features),
                dropped_rows_missing_history_or_values=pump_drop[0] + tank_drop[0],
                dropped_rows_non_finite=pump_drop[1] + tank_drop[1],
            ),
        )

    def build_pump_features(self, frame: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame, tuple[int, int]]:
        """Create pump features using only each pump's current and past values."""

        return self._build_family(
            frame=frame,
            group_columns=("station_id", "pump_id"),
            feature_names=PUMP_ANOMALY_FEATURE_NAMES,
            base_columns=(
                "flow_rate", "pressure", "motor_current", "pump_temperature",
                "error_count", "working_duration", "data_quality_score",
            ),
            immediate_changes=(
                "flow_rate", "pressure", "motor_current", "pump_temperature", "error_count",
            ),
            offset_changes=(
                ("flow_rate", "flow_rate_change_5min", timedelta(minutes=5)),
                ("motor_current", "motor_current_change_5min", timedelta(minutes=5)),
                ("pump_temperature", "pump_temperature_change_30min", timedelta(minutes=30)),
            ),
            rolling=(
                ("flow_rate", "average_flow_rate_30min", "mean"),
                ("pressure", "pressure_std_30min", "std"),
            ),
        )

    def build_tank_features(self, frame: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame, tuple[int, int]]:
        """Create tank features using only each tank's current and past values."""

        return self._build_family(
            frame=frame,
            group_columns=("station_id", "tank_id"),
            feature_names=TANK_ANOMALY_FEATURE_NAMES,
            base_columns=(
                "tank_level", "true_tank_level", "temperature", "water_level",
                "error_count", "data_quality_score",
            ),
            immediate_changes=("tank_level", "temperature", "water_level", "error_count"),
            offset_changes=(
                ("temperature", "temperature_change_30min", timedelta(minutes=30)),
                ("water_level", "water_level_change_30min", timedelta(minutes=30)),
            ),
            rolling=(),
        )

    @staticmethod
    def _prepare(raw: pd.DataFrame) -> pd.DataFrame:
        required = set(METADATA_COLUMNS) | {
            "flow_rate", "pressure", "motor_current", "pump_temperature", "error_count",
            "working_duration", "data_quality_score", "tank_level", "true_tank_level",
            "temperature", "water_level",
        }
        missing = sorted(required - set(raw.columns))
        if missing:
            raise ValueError(f"Training dataset is missing required columns: {', '.join(missing)}.")
        frame = raw.copy()
        frame["reading_timestamp"] = pd.to_datetime(frame["reading_timestamp"], utc=True)
        for column in required - set(METADATA_COLUMNS):
            frame[column] = pd.to_numeric(frame[column], errors="coerce")
        return frame.sort_values(
            ["reading_timestamp", "station_id", "pump_id", "tank_id", "sequence_number"],
            kind="stable", na_position="last",
        ).reset_index(drop=True)

    def _build_family(
        self,
        *,
        frame: pd.DataFrame,
        group_columns: tuple[str, str],
        feature_names: tuple[str, ...],
        base_columns: tuple[str, ...],
        immediate_changes: tuple[str, ...],
        offset_changes: tuple[tuple[str, str, timedelta], ...],
        rolling: tuple[tuple[str, str, str], ...],
    ) -> tuple[pd.DataFrame, pd.DataFrame, tuple[int, int]]:
        if frame.empty:
            return self._empty(feature_names)
        work = frame.copy()
        work["_row_id"] = np.arange(len(work))
        work["hour_of_day"] = work["reading_timestamp"].dt.hour.astype(float)
        work["day_of_week"] = work["reading_timestamp"].dt.dayofweek.astype(float)
        work["is_weekend"] = (work["day_of_week"] >= 5).astype(float)
        grouped = work.groupby(list(group_columns), sort=False, dropna=False)
        for column in immediate_changes:
            work[f"{column}_change"] = grouped[column].diff()
        for column, output, offset in offset_changes:
            work[output] = self._offset_change(work, group_columns, column, offset)
        for column, output, aggregation in rolling:
            work[output] = self._time_rolling(work, group_columns, column, aggregation)

        candidates = work.loc[:, list(METADATA_COLUMNS) + list(feature_names)]
        feature_values = candidates.loc[:, list(feature_names)].to_numpy(dtype=float)
        non_finite_mask = np.isinf(feature_values).any(axis=1)
        missing_mask = np.isnan(feature_values).any(axis=1)
        non_finite = int(non_finite_mask.sum())
        missing_history_or_values = int((missing_mask & ~non_finite_mask).sum())
        candidates = candidates.replace([np.inf, -np.inf], np.nan)
        complete = candidates.dropna(subset=list(feature_names)).copy()
        metadata = complete.loc[:, list(METADATA_COLUMNS)].reset_index(drop=True)
        features = complete.loc[:, list(feature_names)].reset_index(drop=True)
        return features, metadata, (missing_history_or_values, non_finite)

    @staticmethod
    def _offset_change(
        frame: pd.DataFrame,
        group_columns: tuple[str, str],
        value_column: str,
        offset: timedelta,
    ) -> pd.Series:
        """Current value minus the newest value no later than the past offset."""

        left = frame.loc[:, ["_row_id", "reading_timestamp", *group_columns, value_column]].sort_values("reading_timestamp")
        right = left.loc[:, ["reading_timestamp", *group_columns, value_column]].rename(
            columns={"reading_timestamp": "_available_at", value_column: "_past_value"}
        )
        right["_available_at"] = right["_available_at"] + offset
        merged = pd.merge_asof(
            left, right.sort_values("_available_at"), left_on="reading_timestamp",
            right_on="_available_at", by=list(group_columns), direction="backward",
        )
        changes = pd.Series(
            merged[value_column].to_numpy() - merged["_past_value"].to_numpy(),
            index=merged["_row_id"], dtype=float,
        )
        return changes.reindex(frame["_row_id"]).set_axis(frame.index)

    @staticmethod
    def _time_rolling(
        frame: pd.DataFrame,
        group_columns: tuple[str, str],
        value_column: str,
        aggregation: str,
    ) -> pd.Series:
        """Calculate a trailing 30-minute statistic without future observations."""

        values = pd.Series(index=frame.index, dtype=float)
        for _, group in frame.groupby(list(group_columns), sort=False, dropna=False):
            rolling = group.rolling("30min", on="reading_timestamp", closed="both")[value_column]
            result = rolling.mean() if aggregation == "mean" else rolling.std()
            values.loc[group.index] = result.to_numpy()
        return values

    @staticmethod
    def _empty(feature_names: tuple[str, ...]) -> tuple[pd.DataFrame, pd.DataFrame, tuple[int, int]]:
        return (
            pd.DataFrame(columns=list(feature_names)),
            pd.DataFrame(columns=list(METADATA_COLUMNS)),
            (0, 0),
        )
